export const LOGIN_ROUTE = "/login"
export const REGISTARTION_ROUTE = "/registartion"
export const SHOP_ROUTE = "/shop"
export const MAIN_ROUTE = "/"
export const BASKET_ROUTE = "/basket"
export const ITEM_ROUTE = "/item"
export const ABOUT_ROUTE = "/about"
export const CONTACTS_ROUTE = "/contacts"